name: translator_tool
description: Language learning app with dual translation toggle

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9

  # HTTP Client
  dio: ^5.3.2

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI Components
  cupertino_icons: ^1.0.6

  # Utilities
  collection: ^1.18.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing
  integration_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.7

  # Code Generation
  hive_generator: ^2.0.1

  # Linting
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_intl:
  enabled: true